##################################################################
# Welcome to Config!
# This config is very easy to configurate.
#############################################################


## Messages
messages:
  # This message is used to send to Console when use /job command.
  # Job Command can use only by Players.
  consoleMessage: "&cYou can't use this command as Console Command Sender."

  # Message what appereal first before Options when you use /job command.
  # If you don't one, just use " " or "" and that is.
  messageTitleJobWindow: "                       Hello!\n           Welcome to Job Category!\n    Select what you want to do from now."

  # Message what is sended when a player got a job
  receiveJob: "&7» &3You have successfully selected Job: &b%job &3!"

  # Title of Window 'Without Job'
  withoutJobTitleWindow: "Without Job Option"

  # Info Message who is sended when Player acces Info - tap button of Info
  infoMessage: "                      Hello!\n            Welcome to Info Jobs!\n\n
  §c» §aLumberJack:\n
  §eWith that Job you can get money if you cut wood, any type of wood.\n
  §eThe sum received per block: §72.5$\n\n
  §c» §aMiner: \n
  §eYou can make money if you are going to work with this job.\n
  §eEncount money only if you are mining CobbleStone and Precious Ores.\n
  §eThe sum received per block: §72.5$\n\n
  §c» §aFarmer: \n
  §eYou can make money with this job if you plant.\n
  §eAnd You only accept money if you Plant or Cultivate Seeds, any kind of Seeds, Saplings and Flowers.\n
  §eThe sum received per block: §71$\n\n
  §c» §aKiller:\n
  §eWith this Job you can make money if you kill or hit non-spawn players.\n
  §eThe sum received per hit: §70.4$\n
  §eSum received per kill: §73$\n\n
  §c» §aHunter:\n
  §eWith this Job you can make money if you kill or hit animals.\n
  §eThe sum received per hit: §70.4$\n
  §eSum received per kill: §71.4$\n"

  # Without Job Message Sended to Player
  withoutJobMessage: "&7» &3From now, you don't have One Job &3!"


## Icons Link
##
## If you don't want Icons, just use " " or "" and that is.
icons:

  # LumberJack
  lumberJackIcon: "https://i.imgur.com/uWmtrax.png"
  # Miner
  minerIcon: "https://i.imgur.com/XFCYdCz.png"
  # Farmer
  farmerIcon: "https://i.imgur.com/otMDlEU.png"
  # Killer
  killerIcon: "https://i.imgur.com/YHkAa4q.png"
  # Hunter
  hunterIcon: "https://i.imgur.com/HpwAZvq.png"
  # Info
  infoIcon: "https://i.imgur.com/nujWKR3.png"
  # WithoutJob
  withoutJobIcon: "https://i.imgur.com/YXBNPBc.png"


