name: CoreJobs-Nukkit
main: nycuro.CoreJobsMain
version: "1.0"
api: ["1.0.0"]
author: NycuRO
description: Very Basic plugin Jobs for Nukkit with Forms. More coming soon.

commands:
  job:
    description: Select a Job
    usage: "/job"
    permission: core.job

permissions:
  core.job:
    description: "Teleport to Spawn!"
    default: true